### ISSUE TITLE
Deploy prod and staging sites to CI/CD

### ISSUE THREAD

**Issue by jlaprise** [webonyx/atlas-component-library#1]
The application to be deployed is `yarn run build-storybook` vs. `yarn run build` which the base CRA app.

Staging: https://staging.team.us/design-system (develop)
Prod: https://atlas.att.com/design-system (master)

**Comment by jlaprise** [comment]
Both URLs load a blank white screen.

![image](https://user-images.githubusercontent.com/245091/153926929-f93c05ba-5d65-44ed-9e00-255238aca1cb.png)

**Comment by phamviet** [comment]
Due too their Storybook  design You need to append `/` to the end of url https://staging.team.us/design-system/. I will configure Load Balancer to do that automatically.
